name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Build and Push
      run: |
        set VERSION=$(date +%s)
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag fscottmiller/octo:%VERSION%
        docker push fscottmiller/octo:%VERSION%
      
